parameters:
  name: ''
  pool: ''
  solutionPath: ''
  solutionName: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  
  steps:

  - template: ../steps/install-powerapps-tools.yml 

 - task: PowerAppsPackSolution@0
    inputs:
      SolutionSourceFolder: '$(Build.SourcesDirectory)\${{ parameters.solutionPath }}\${{ parameters.solutionName }}'
      SolutionOutputFile: '$(Pipeline.Workspace)\${{ parameters.solutionName }}.zip'
      SolutionType: Both

  - publish: $(Pipeline.Workspace)\${{ parameters.solutionName }}_managed.zip
    artifact: drop
    displayName: "Publish pipeline artifact - ${{ parameters.solutionName }}_managed.zip as drop"