parameters:
  name: ''
  pool: ''
  powerAppsEnvironment: ''
  solutionName: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  
  steps:
  - template: install-powerapps-tools.yml 

  - task: PowerAppsImportSolution@0
    inputs:
      PowerAppsEnvironment: '${{ parameters.powerAppsEnvironment }}'
      SolutionInputFile: '$(Pipeline.Workspace)\drop\${{ parameters.solutionName }}_managed.zip'
      ConvertToManaged: false
      OverwriteUnmanagedCustomizations: true
      HoldingSolution: false
      SkipProductUpdateDependencies: true
      PublishWorkflows: true