parameters:
  name: ''
  pool: {}
  targetEnvironment: '' # Azure DevOps Environment
  powerAppsEnvironment: '' # PowerApps Service Connection
  solutionName: ''
  
jobs:

    - deployment: ${{ parameters.name }}
      displayName: "Deploy managed solution to downstream environments"

      pool: ${{ parameters.pool }}
      
      environment: ${{ parameters.targetEnvironment }}

      strategy:
        runOnce:
          deploy:
      
            steps:
  
            - template: install-powerapps-tools.yml 

            - task: PowerAppsImportSolution@0
              inputs:
                PowerAppsEnvironment: '${{ parameters.powerAppsEnvironment }}'
                SolutionInputFile: '$(Pipeline.Workspace)\drop\${{ parameters.solutionName }}_managed.zip'
                ConvertToManaged: false
                OverwriteUnmanagedCustomizations: true
                HoldingSolution: false
                SkipProductUpdateDependencies: true
                PublishWorkflows: true