parameters:
  name: ''
  pool: {}
  # Azure Pipeline Environment
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops
  pipelineEnvironment: '' 
  powerAppsEnvironment: '' # PowerApps Service Connection
  solutionName: ''
  AsyncOperation: true
  MaxAsyncWaitTime: '240'

jobs:

    - deployment: ${{ parameters.name }}
      displayName: "Deploy managed solution to downstream environments"

      pool: ${{ parameters.pool }}
      
      environment: ${{ parameters.pipelineEnvironment }}

      strategy:
        runOnce:
          deploy:
      
            steps:
            # Deployment jobs automatically download pipeline artifacts
            # Ref: https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#artifacts-in-release-and-deployment-jobs

            - template: install-powerapps-tools.yml 

            - task: PowerAppsImportSolution@0
              inputs:
                PowerAppsEnvironment: '${{ parameters.powerAppsEnvironment }}'
                SolutionInputFile: '$(Pipeline.Workspace)\solution-artifact\${{ parameters.solutionName }}_managed.zip'
                AsyncOperation: ${{ parameters.AsyncOperation }}
                MaxAsyncWaitTime: ${{ parameters.MaxAsyncWaitTime }}
