parameters:
  name: 'Build_Test_Solution'
  vmImage: ''
  buildEnvironment: ''
  solutionPath: ''
  solutionName: ''

stages:

- stage: ${{ parameters.name }}
  jobs:
  - job:
    displayName: "Build & Test Solution"
  
    pool:
      vmImage: ${{ parameters.vmImage }}
    
    steps:
      - template: ../steps/solution-management/solution-build-pack-solution.yml
        parameters: 
          solutionPath: '${{ parameters.solutionPath }}'
          solutionName: '${{ parameters.solutionName }}'
      - template: ../steps/solution-management/solution-build-create-managed-artifact.yml
        parameters: 
          powerAppsEnvironment: '${{ parameters.buildEnvironment }}'
          solutionName: '${{ parameters.solutionName }}'
