parameters:
  name: 'Build_Test_Solution'
  vmImage: ''
  buildEnvironment: ''
  solutionPath: ''
  solutionName: ''
  powerAppsChecker.rulesetId: ''
  powerAppsChecker.clientId: ''
  powerAppsChecker.clientSecret: ''
  azure.geography: ''
  azure.tenantId: ''

stages:

- stage: ${{ parameters.name }}
  jobs:
  - job:
    displayName: "Build & Test Solution"
  
    pool:
      vmImage: ${{ parameters.vmImage }}
    
    steps:
      - template: ../steps/solution-build-pack-solution.yml
        parameters: 
          solutionPath: '${{ parameters.solutionPath }}'
          solutionName: '${{ parameters.solutionName }}'
      - template: ../../stages/powerapps-checker.yml
        parameters:
          powerAppsChecker.rulesetId: ''
          powerAppsChecker.clientId: ''
          powerAppsChecker.clientSecret: ''
          solutionName: 'parameters.solutionName'
          azure.geography: ''
          azure.tenantId: ''
          vmImage: 'parameters.vmImage'
      - template: ../steps/solution-build-create-managed-artifact.yml
        parameters: 
          powerAppsEnvironment: '${{ parameters.buildEnvironment }}'
          solutionName: '${{ parameters.solutionName }}'
