parameters:
  artifact.name: 'solution'
  name: 'Build_Solution'
  solution.name: ''
  solution.path: 'xml'
  vmImage: 'windows-latest'

stages:

- stage: ${{ parameters.name }}
  jobs:
  - job:
    displayName: "Build Solution"
  
    pool:
      vmImage: ${{ parameters.vmImage }}
    
    steps:
    - template: ../steps/install-powerapps-tools.yml

    - task: PowerAppsPackSolution@0
      inputs:
        SolutionSourceFolder: '$(Build.SourcesDirectory)\${{ parameters.solution.path }}'
        SolutionOutputFile: '$(Pipeline.Workspace)\artifact\${{ parameters.solution.name }}.zip'
        SolutionType: Both
    
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(solution.path)/..'
        contents: 'solution.json'
        targetFolder: $(Pipeline.Workspace)\artifact
      
    - publish: '$(Pipeline.Workspace)\artifact'
      artifact: ${{ parameters.artifact.name }}