parameters:
  jobProperties: {}
  solutionJsonPath: 'solution.json'
  solutionOutputFile: '$(Pipeline.Workspace)\packed-solution\$(solutionName).zip'
  solutionType: 'Both'
  toolset: 'powerapps-build-tools'
  toolsDirectory: '$(Pipeline.Workspace)\tools'

jobs:
- job: ${{ coalesce(parameters.jobProperties.name, 'Build') }}

  ${{ if eq(parameters.jobProperties.pool, '') }}:
    pool:
      vmImage: 'windows-latest'
  
  ${{ each pair in parameters.jobProperties }}:
    ${{ if not(in(pair.key, 'name', 'pool')) }}:
      ${{ pair.key }}: ${{ pair.value }}

  steps:
  - template: ../steps/install-tools.yml
    parameters:
      toolset: ${{ parameters.toolset }}
      toolsDirectory: ${{ parameters.toolsDirectory }}
  
  - template: ../steps/pack-solution.yml
    parameters:
      solutionJsonPath: ${{ parameters.solutionJsonPath }}
      solutionOutputFile: ${{ parameters.solutionOutputFile }}
      solutionType: ${{ parameters.solutionType }}
      toolset: ${{ parameters.toolset }}
      toolsDirectory: ${{ parameters.toolsDirectory }}
  
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: drop
    displayName: 'Publish build artifacts'
    enabled: false