parameters:
  jobProperties: {}
  solutionJsonPath: 'solution.json'
  toolset: 'powerapps-build-tools'
  toolsDirectory: '$(Pipeline.Workspace)\tools'

jobs:
- job:
  ${{ if eq(parameters.jobProperties.name, '') }}:
    name: 'Build'

  ${{ if eq(parameters.jobProperties.pool, '') }}:
    pool:
      vmImage: 'windows-latest'
  
  ${{ each pair in parameters.jobProperties }}:
    ${{ if not(in(pair.key, 'name', 'pool')) }}:
      ${{ pair.key }}: ${{ pair.value }}

  steps:
  - template: ../steps/install-tools.yml
    parameters:
      toolset: ${{ parameters.toolset }}
      toolsDirectory: ${{ parameters.toolsDirectory }}
  
#  - template: ../steps/pack-solution.yml
#    parameters:
#      solutionJsonPath: ${{ parameters.solutionJsonPath }}
#      toolset: ${{ parameters.toolset }}
#      toolsDirectory: ${{ parameters.toolsDirectory }}
  
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: drop
    displayName: 'Publish build artifacts'
    enabled: false