parameters:
  name: 'Release'
  dependsOn: 'Test'
  condition: 'succeeded(''Test'')'
  vmImage: 'windows-latest'

stages:
- stage: ${{ parameters.name }}

  ${{ if neq(parameters.dependsOn, '') }}:
    dependsOn: ${{ parameters.dependsOn }}
  
  ${{ if neq(parameters.condition, '') }}:
    condition: ${{ parameters.condition }}

  jobs:
  - deployment: Deploy
    displayName: "Import solution artifact"

    pool:
      vmImage: ${{ parameters.vmImage }}
    
    environment: test
    strategy:
      runOnce:
        deploy:

          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          
          - powershell: Install-Module Microsoft.Xrm.Data.Powershell -Scope CurrentUser -Force
            displayName: 'Install Microsoft.Xrm.Data.PowerShell'

          - powershell: |
              Write-Host `
                ("AuthType = Office365;" + `
                  "Username = $(serviceAccount.upn);" + `
                  "Password = $(serviceAccount.password);" + `
                  "Url = https://$(environment.uniqueName).crm.dynamics.com")
              
              $connection = Get-CrmConnection `
                -ConnectionString `
                  ("AuthType = Office365;" + `
                  "Username = $(serviceAccount.upn);" + `
                  "Password = $(serviceAccount.password);" + `
                  "Url = https://$(environment.uniqueName).crm.dynamics.com")

              Import-CrmSolutionAsync `
                -BlockUntilImportComplete `
                -conn $connection `
                -SolutionFilePath $(System.ArtifactsDirectory)\drop\packedSolution\$(solution.name)_managed.zip
            displayName: 'Import solution'