stages:
- stage: Test

  dependsOn: Build
  condition: succeeded('Build')

  jobs:
    - job:
      displayName: 'Run PowerApps Checker'

      pool:
        vmImage: 'vs2017-win2016'

      steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop'
          downloadPath: '$(System.ArtifactsDirectory)'
        
      - powershell: Install-Module -Name Microsoft.PowerApps.Checker.PowerShell -Scope CurrentUser -Force
        displayName: 'Install Microsoft.PowerApps.Checker.PowerShell'
      
      - powershell: |
          md '$(Common.TestResultsDirectory)\powerapps-checker'
          $rulesets = Get-PowerAppsCheckerRulesets -Geography $(azure.geography)
          Invoke-PowerAppsChecker `
            -Geography $(azure.geography) `
            -ClientApplicationId $(powerAppsChecker.clientId) `
            -TenantId $(azure.tenantId) `
            -Ruleset $rulesets `
            -FileUnderAnalysis '$(System.ArtifactsDirectory)\drop\packedSolution\$(solution.name)_managed.zip' `
            -OutputDirectory '$(Common.TestResultsDirectory)\powerapps-checker' `
            -ClientApplicationSecret (ConvertTo-SecureString -AsPlainText -Force -String '$(powerAppsChecker.clientSecret)')
        displayName: 'Invoke PowerApps Checker'

      - powershell: md '$(Common.TestResultsDirectory)\powerapps-checker\unzipped'
        displayName: 'Create folder for unzipped results'

      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: '$(Common.TestResultsDirectory)\powerapps-checker\*.zip'
          destinationFolder: '$(Common.TestResultsDirectory)\powerapps-checker\unzipped'
        displayName: 'Extract results to folder'
      
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Common.TestResultsDirectory)\powerapps-checker\unzipped'
          artifactName: CodeAnalysisLogs
        displayName: 'Publish PowerApps Checker report artifacts'